AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apitest-app

  Sample SAM Template for apitest-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MyGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_get_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        MyGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /myget
            Method: get
            RestApiId:
              Ref: MyApi
      Layers:
        - !Ref MyLayer

  MyPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_post_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        MyGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mypost
            Method: post
            RestApiId:
              Ref: MyApi
      Layers:
        - !Ref MyLayer

  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my_layer
      Description: My layer description
      ContentUri: my_layer/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        # AllowCredentials: true
        AllowMethods: "'OPTIONS,GET,POST'"
        # AllowMethods: "'OPTIONS'"
        AllowHeaders: "'Content-Type'"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyGetApi:
    Description: "API Gateway endpoint URL for Prod stage for my get function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/myget/"
  MyGetFunction:
    Description: "My Get Lambda Function ARN"
    Value: !GetAtt MyGetFunction.Arn
  MyGetFunctionIamRole:
    Description: "Implicit IAM Role created for My Get function"
    Value: !GetAtt MyGetFunctionRole.Arn

  MyPostApi:
    Description: "API Gateway endpoint URL for Prod stage for my post function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mypost/"
  MyGetFunction:
    Description: "My Post Lambda Function ARN"
    Value: !GetAtt MyPostFunction.Arn
  MyGetFunctionIamRole:
    Description: "Implicit IAM Role created for My Post function"
    Value: !GetAtt MyPostFunctionRole.Arn
